### ISSUE TITLE
Equivalence for `#uplcHash` in the haskell backend when variables are involved

### ISSUE THREAD

**Issue by gtrepta** [runtimeverification/plutus-core-semantics#242]
In `simple-proofs/verification.k` we have the following simplification rule for `#uplcHash`:
```
  rule {#uplcHash(V1) #Equals #uplcHash(V2)} => {V1 #Equals V2} [simplification]
```
This has been working fine so far, but I have run into a case where this rule will not rewrite:
```
  claim <k> v_x => X ... </k>
        <env>
          v_x |-> ListItem( #uplcHash( X ) )
          v_f |-> ListItem( #uplcHash( F ) )
          => ?_
        </env>
        <heap>
          #uplcHash( X ) |-> X
          #uplcHash( F ) |-> F
          => ?_
        </heap>
          requires X ==K < con integer _I:Int >
           andBool F ==K < lam v_f (con unit ()) .Map >
```
Trying to run the proof on this claim will cause a branch immediately, with the configuration on one branch getting stuck on this:
```
  <generatedTop>
    <k>
      v_x ~> _DotVar1:K
    </k>
    <env>
      v_f |-> ListItem ( #uplcHash ( < lam v_f ( con unit () ) .Map > ) )
      v_x |-> ListItem ( #uplcHash ( < con integer _I:Int > ) )
    </env>
    <heap>
      #uplcHash ( < con integer _I:Int > ) |-> < con integer _I:Int >
      #uplcHash ( < lam v_f ( con unit () ) .Map > ) |-> < lam v_f ( con unit () ) .Map >
    </heap>
    <trace>
      _Gen3:List
    </trace>
  </generatedTop>
#And
  {
    #uplcHash ( < con integer _I:Int > )
  #Equals
    #uplcHash ( < lam v_f ( con unit () ) .Map > )
  }
```

I believe the symbolic variable `_I` in the integer constant is involved in some way that prevents the ML expression from simplifying.

**Comment by SchmErik** [comment]
@gtrepta I'm not sure if I'm directly answering the issue here but this looks strange

> ```
> #And
>   {
>     #uplcHash ( < con integer _I:Int > )
>   #Equals
>     #uplcHash ( < lam v_f ( con unit () ) .Map > )
>   }
> ```
> 
> I believe the symbolic variable `_I` in the integer constant is involved in some way that prevents the ML expression from simplifying.

this is false

**Comment by gtrepta** [comment]
Yes it should, but it doesn't evaluate at all.

**Comment by SchmErik** [comment]
Which rule does this transition? I've been using the `rules` command to get the axiom that applied. Maybe this command might be helpful for you

**Comment by SchmErik** [comment]
Maybe it's the requires clause:
```
          requires X ==K < con integer _I:Int >
           andBool F ==K < lam v_f (con unit ()) .Map >
```
I'm writing this off the top of my head but does something like this make a difference?
```
          requires (X ==K < con integer _I:Int >)
           andBool (F ==K < lam v_f (con unit ()) .Map >)
```

**Comment by gtrepta** [comment]
I don't think it's that, X and F are showing up in the configuration properly without issue.

**Comment by PetarMax** [comment]
Hmmm, the claim is passing for me - can't figure out what changed so that it now passes?

**Comment by gtrepta** [comment]
I'm no longer suspicious of the symbolic variable being the cause, I reproduced it with concrete values. Virgil also found it strange, so I've opened an issue on the haskell backend with a minimal example: [#3129](https://github.com/runtimeverification/haskell-backend/issues/3129)

**Comment by PetarMax** [comment]
@gtrepta Yes, that is what I was doing - I wasn't aware that it's possible to get false positives, how does that happen?

**Comment by gtrepta** [comment]
Closing this since the heap has been removed and it no longer needs to be addressed here. The issue with a minimal example on the haskell backend board remains open.
