### ISSUE TITLE
Simplify `(force A) => A`, where A is a partial application.

### ISSUE THREAD

**Issue by ChristianoBraga** [runtimeverification/plutus-core-semantics#259]
Page 14 of Plutus specification has a rule specifying `(force A) => A`, where `A` is a partial application. The following rule could perhaps be added to `KPlutus` semantics
`rule (force < buintin BN L N >) => < builtin BN L N > requires N < #numArgs(BN)` where `BN` is a `BuiltinName`, `L` is `List` and `N` is an `Int`.

**Comment by SchmErik** [comment]
Here's an example that I ran:
`(program 1.0.0 (force [(builtin addInteger) (con integer 1) ] ) )`
and I got this result:
```
$ uplc evaluate -i p
An error has occurred:  error:
A builtin expected a term argument, but something else was received
Caused by: (force (addInteger 1))
```
So it sounds like this statement doesn't work for any partially applied builtins.

**Comment by PetarMax** [comment]
What happens when you try`(program 1.0.0 [ (force [(builtin addInteger) (con integer 1) ] ) (con integer 2) ])`? Is it possible that the force is discharged correctly but partial applications of built-ins aren't allowed to stay partial?

**Comment by SchmErik** [comment]
```
$ uplc evaluate -i test1 
An error has occurred:  error:
A builtin expected a term argument, but something else was received
Caused by: (force (addInteger 1))

```

**Comment by gtrepta** [comment]
`(force M)` rewrites to `M ~> Force`. So `(force [(builtin addInteger) (con integer 1) ] )` will rewrite to `< builtin addInteger listItem(<con integer 1>) | listItem(int) > ~> Force`, which is malformed (the partial application needs an integer, but the `Force` will kick the `int` out of the remaining parameters list).

`(force <builtin ...>)` doesn't even exist in the syntax:
```
  syntax Term ::= UplcId
...
                | "(" "force" Term ")"
```

**Comment by gtrepta** [comment]
I reviewed the rule on page 14. An important thing to note is that it specifies $next(A) \in Q$, which makes sense because `force` is meant to skip type instantiation for uplc. I think we already have this rule covered with the changes introduced by #262 .

**Comment by PetarMax** [comment]
Specifically:

```
  rule <k> < builtin BN:BuiltinName L | ListItem(_:Quantification) E > ~> Force =>
           < builtin BN L | E > ... </k>
  requires notBool E ==K .List
```

looks like the relevant one?

**Comment by gtrepta** [comment]
Yes, that's the one.

**Comment by ChristianoBraga** [comment]
Closing this issue as `(force A) => A` seems to be derivable from CEK rules.
