### ISSUE TITLE
fstPair, sndPair, and chooseList requires (force (force ... )) to evaluate on uplc

### ISSUE THREAD

**Issue by SchmErik** [runtimeverification/plutus-core-semantics#260]
The following program exhibits divergent behavior between `uplc` and `kplc`:
```
(program 1.0.0
  [ (force (force (builtin fstPair)))
    [(builtin mkPairData)
      [(builtin bData) (con bytestring #00) ]
      [(builtin bData) (con bytestring #FF) ]
    ]
  ]
)
```
We need to re-examine the spec and fix kplc to match uplc behavior. This program evaluates to a stuck term on `uplc` and `kplc` evaluates to `(con data #4100)`

**Comment by SchmErik** [comment]
This is likely the root-cause of the large environment size. After adding this patch to the current head cdb1fc8505a775897bd817a80da21cb7c1cdcff4 

```
diff --git a/uplc-polymorphic-builtins.md b/uplc-polymorphic-builtins.md
index 7c9e166..ef6d439 100644
--- a/uplc-polymorphic-builtins.md
+++ b/uplc-polymorphic-builtins.md
@@ -76,7 +76,7 @@ return an error if `fstPair`'s argument is not a pair.
   rule #typeCheck(ListItem(< con pair (_:TypeConstant) (_:TypeConstant) (_,_) >),
                              fstPair, 1) => true
 
-  rule <k> (builtin fstPair) ~> Force => < builtin fstPair .List 1 >  ... </k>
+  rule <k> (builtin fstPair) ~> Force ~> Force => < builtin fstPair .List 1 >  ... </k>
        <env> _ => .Map </env>
 
   rule <k> #eval(fstPair,
@@ -97,7 +97,7 @@ return an error if `sndPair`'s argument is not a pair.
   rule #typeCheck(ListItem(< con pair (_:TypeConstant) (_:TypeConstant) (_,_) >),
                              sndPair, 1) => true
 
-  rule <k> (builtin sndPair) ~> Force => < builtin sndPair .List 1 >  ... </k>
+  rule <k> (builtin sndPair) ~> Force ~> Force => < builtin sndPair .List 1 >  ... </k>
        <env> _ => .Map </env>
 what's expected 
   rule <k> #eval(sndPair,
@@ -121,7 +121,7 @@ return an error if `sndPair`'s argument is not a pair.
                   ListItem(_:Value),
                   chooseList, 3) => true
 
-  rule <k> (builtin chooseList) ~> Force => < builtin chooseList .List 3 > ... </k>
+  rule <k> (builtin chooseList) ~> Force ~> Force => < builtin chooseList .List 3 > ... </k>
        <env> _ => .Map </env>
 
   rule <k> #eval(chooseList,
```
I get this when running the "trivial minting policy" attached. Note: this was the contract generated from a trivial minting policy and with the bytestring encoding of data by converted hand to the textual format.

```
$ kplc run ../freeTest.uplc
== /home/erik/plutus-core-semantics/.build/usr/bin/kplc: krun --directory /home/erik/plutus-core-semantics/.build/usr/lib/kplutus/llvm ../freeTest.uplc
<generatedTop>                                                            
  <k>                                                                                        
    [] ( delay ( lam v_419 v_419 ) ) ~> .
  </k>
  <env>                                                                             
    .Map                                                                                     
  </env>                                                 
  <trace>
    .List                                                             
  </trace>                                                                                                                                                                                                                                                                                                                                                                          
</generatedTop>
```

This K term is similar to the term that uplc produces when the flat-encoded version of the file is run on uplc. I think my patch likely needs more testing as these force terms may not appear consecutively in all cases...

[freeTest.txt](https://github.com/runtimeverification/plutus-core-semantics/files/9135860/freeTest.txt)

**Comment by gtrepta** [comment]
Semantics of the CEK machine involving builtins:
![cekbuiltins](https://user-images.githubusercontent.com/50716988/179863720-78d1c859-25bd-4cc0-ad39-9d94c157719a.png)

We have the last two steps implemented. But we're handling steps 2 and 3 with a hack for step 1 (`(builtin BN:PolyBuiltinName) ~> Force => < builtin BN ... >`).

So it would be good to get our semantics to properly represent these steps.

**Comment by gtrepta** [comment]
@ChristianoBraga and I discussed this and we think we understand what's going on here.

The type signature for `fstPair` is the following:
```
[∀a#, ∀b#, pair (a#, b#)] → a#
```
Notice that it takes three arguments, with the first two being quantifications of polymorphic builtin type variables. `ι ∈ Q` indicates that type variable `ι` is in the set of all quantifications, which is listed as a side-condition in rules 2 and 3.

Section 4.3 of the plutus core specification says that in typed plutus core, quantifications need to be instantiated as concrete types, but in untyped plutus the instantiation is replaced by an application of `force`. That's what rules 2 and 3 represent in the above diagram.

So the program in the first card should progress something like this:
```
(force (force (builtin fstPair))) ...
(force (builtin fstPair)) ~> Force ...
(builtin fstPair) ~> Force ~> Force ...
< builtin fstPair [] [∀a#, ∀b#, pair(a#, b#)] > ~> Force ~> Force ...
< builtin fstPair [] [∀b#, pair(a#, b#)] > ~> Force ...
< builtin fstPair [] [pair(a#, b#)] > ~> [_ [(builtin mkPairData) ...] RHO ] ...
[(builtin mkPairData) ...] ~> [< builtin fstPair [] [pair (a#, b#)] > _] ...
...
< con pair(bytestring)(bytestring) (#00, #FF) > ~> [< builtin fstPair [] [pair(a#, b#)] > _] ...
#eval( < builtin fstPair [ < con pair(bytestring)(bytestring) (#00, #FF) > ] [] > ) ...
< con bytestring #00 > ...
```

The actual type instantiation of `a#` and `b#` to `bytestring` I think doesn't happen in untyped plutus. It's just assumed that the uplc code coming in is well-formed. This is just a hunch, I haven't confirmed it yet.
