### ISSUE TITLE
Integrate blockchain plugin with KPlutus

### ISSUE THREAD

**Issue by ChristianoBraga** [runtimeverification/plutus-core-semantics#87]
The idea is to be able to call the blockchain plugin API to implement `sha2_256` and `sha3_256` KPlutus builtins.

1. Blockchain plugin 
https://github.com/runtimeverification/blockchain-k-plugin

2. This is an example of how to incoporate the blockchain-k-plugin into the KEVM build system which can be used as a guide for incorporating it into the KPlutus build system.
https://github.com/kframework/evm-semantics/blob/master/Makefile#L147

**Comment by ehildenb** [comment]
Let's get to the point where we can do `imports KRYPTO` in the `UPLC` module, and it builds correctly on CI. Then later we can worry about using/testing the krypto hooks.
